org: ${env:SLS_ORG}
service: disdb-auth-api

provider:
  name: aws
  runtime: python3.9
  iam:
    role: ${env:AWS_ROLE_ARN}
  memorySize: 1024
  timeout: 29
  environment:

    # Tables
    TABLE_USERS: ${sls:stage}-auth-user-table
    TABLE_TOKENS: ${sls:stage}-tokens-table

    # Index
    INDEX_EMAIL_USERS: email-index

    # Service info
    SERVICE_NAME: disdb-auth-api
    STAGE: ${sls:stage}

    # Function names
    VALIDATE_TOKEN_FUNCTION: validateToken

functions:
  registerUser:
    handler: registerUser.lambda_handler
    events:
      - http:
          path: auth/register
          method: post
          cors: true

  validateToken:
    handler: validateToken.lambda_handler
    events:
      - http:
          path: /token/validate
          method: post
          cors: true

resources:
  Resources:
    AuthUsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.TABLE_USERS}
        AttributeDefinitions:
          - AttributeName: user_id
            AttributeType: S
          - AttributeName: email
            AttributeType: S
        KeySchema:
          - AttributeName: user_id
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: ${self:provider.environment.INDEX_EMAIL_USERS}
            KeySchema:
              - AttributeName: email
                KeyType: HASH
            Projection:
              ProjectionType: ALL
        BillingMode: PAY_PER_REQUEST
        PointInTimeRecoverySpecification:
          PointInTimeRecoveryEnabled: true

    TokensTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.TABLE_TOKENS}
        AttributeDefinitions:
          - AttributeName: token
            AttributeType: S
        KeySchema:
          - AttributeName: token
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        PointInTimeRecoverySpecification:
          PointInTimeRecoveryEnabled: true
