org: ${env:SLS_ORG}
service: currency-api

provider:
  name: aws
  runtime: python3.12
  iam:
    role: ${env:AWS_ROLE_ARN}
  memorySize: 1024
  timeout: 29
  environment:
    TABLE_CURRENCY_CONVERSION: ${sls:stage}-currency-conversion-table
    TABLE_REPORTS: ${sls:stage}-currency-reports-table
    STAGE: ${sls:stage}
    VALIDATE_TOKEN_FUNCTION: disdb-auth-api

functions:
  convertCurrency:
    handler: convertCurrency.lambda_handler
    events:
      - http:
          path: currency/convert
          method: post
          cors: true

  getCurrencyConversionByUserId:
    handler: getCurrencyConversionByUserId.lambda_handler
    events:
      - http:
          path: currency/conversion
          method: get
          cors: true

  updateCurrencyConversion:
    handler: updateCurrencyConversion.lambda_handler
    events:
      - http:
          path: currency/conversion/{conversion_id}
          method: put
          cors: true

  deleteCurrencyConversion:
    handler: deleteCurrencyConversion.lambda_handler
    events:
      - http:
          path: currency/conversion/{conversion_id}
          method: delete
          cors: true

  createReport:
    handler: createReport.lambda_handler
    events:
      - http:
          path: currency/report
          method: post
          cors: true

  getReportsByUser:
    handler: getReportsByUser.lambda_handler
    events:
      - http:
          path: currency/report
          method: get
          cors: true

  updateReport:
    handler: updateReport.lambda_handler
    events:
      - http:
          path: currency/report/{report_id}
          method: put
          cors: true

  deleteReport:
    handler: deleteReport.lambda_handler
    events:
      - http:
          path: currency/report/{report_id}
          method: delete
          cors: true

resources:
  Resources:
    CurrencyConversionTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.TABLE_CURRENCY_CONVERSION}
        AttributeDefinitions:
          - AttributeName: usuario_id
            AttributeType: S
          - AttributeName: conversion_id
            AttributeType: S
        KeySchema:
          - AttributeName: usuario_id
            KeyType: HASH
          - AttributeName: conversion_id
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
        PointInTimeRecoverySpecification:
          PointInTimeRecoveryEnabled: true

    ReportsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.TABLE_REPORTS}
        AttributeDefinitions:
          - AttributeName: usuario_id
            AttributeType: S
          - AttributeName: report_id
            AttributeType: S
        KeySchema:
          - AttributeName: usuario_id
            KeyType: HASH
          - AttributeName: report_id
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
        PointInTimeRecoverySpecification:
          PointInTimeRecoveryEnabled: true
